# Simple workflow for deploying static content to GitHub Pages
name: Deploy static content to Pages

on:
  # Runs on pushes targeting the default branch
  push:
    branches: ['develop']

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# Sets the GITHUB_TOKEN permissions to allow deployment to GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:
  # Single deploy job since we're just deploying
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      
      - name: Install dependencies
        run: npm ci
      
      - name: Build
        run: npm run build

      - name: Add 404 fallback
        run: cp ./dist/index.html ./dist/404.html

      # Step to deploy to another repository
      - name: Checkout target repository
        uses: actions/checkout@v4
        with:
          repository: mohitjain49/mohitjain49.github.io  # Replace with your target repository
          token: ${{ secrets.GITHUB_TOKEN }}
          path: mohitjain49.github.io

      - name: Copy dist folder to target repository
        run: |
          cp -r ./dist/* mohitjain49.github.io/  # Copy contents of dist to target-repo folder

      - name: Commit changes
        run: |
          cd mohitjain49.github.io
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add .
          git commit -m "Deploy static content from develop" || echo "No changes to commit"
          git push origin main  # Push to the 'main' branch of the target repo
          env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
